line-length = 120

target-version = ["py39"]

[lint]
select = ["ALL"]

ignore = [
    # pydocstyle
    "D",
    # flake8-pytest-style
    "PT",
    # flake8-fixme
    "FIX",
    # flake8-print
    "T20",
    # Missing type annotation for self/cls in method
    "ANN10",
    # Checks that function arguments are annotated with a more specific type than Any
    "ANN401",
    # Checks for missing from __future__ import annotations imports upon detecting type annotations that can be written more succinctly under PEP 563
    "FA100",
    # Checks for packages that are missing an __init__.py file
    "INP001",
    # Checks for the use of string literals in exception constructors
    "EM101",
    # Checks for long exception messages that are not defined in the exception class itself
    "TRY003",
    # Checks that a TODO comment includes an author.
    "TD002",
    # Checks that a TODO comment is associated with a link to a relevant issue or ticket.
    "TD003",
    # Checks for function definitions that include too many arguments.
    "PLR0913",
]

[lint.per-file-ignores]
# We're using camelCase in the test framework to be consistent with unittest
"test_framework/*" = ["N802"]
# We import neccecary (but "unused") objects in __init__.py files for public API
"test_framework/**/__init__.py" = ["F401", "F403"]
# We have a function that should be defined in the first step, but unused for some time
"2_2_bar_and_pie_charts_matplotlib/1_theory/[1-8]_*" = ["ARG001"]
# TODO: remove after removing (or fixing) correspoding files
"3_0_histograms_intro/1_overview/[2-5]_*" = ["NPY002"]

[lint.isort]
known-local-folder = ["data", "common", "task"]
force-sort-within-sections = true
order-by-type = true

[lint.flake8-annotations]
suppress-none-returning = true
