line-length = 120

[lint]
select = ["ALL"]

ignore = [
    # pydocstyle
    "D",
    # flake8-print
    "T20",
    # Missing type annotation for self/cls in method
    "ANN10",
    # Checks for missing from __future__ import annotations imports upon detecting type annotations that can be written more succinctly under PEP 563.
    "FA100",
]

[lint.flake8-annotations]
suppress-none-returning = true
